export const routes = Object.freeze({
  PASSWORD_LOGIN: "password login",
  OTP_LOGIN: "otp login",
  REGISTER: "register",
  ADD_PROFILE: "add profile",
  FORGOT_PASSWORD: "forgot password",
  LINK_DEVICE: "link device",
  HOME: "home",
  DEVICE_CONNECTED: "device connected",
  HOME_OTHERS: "home others",
  ADD_TEAM_MEMBERS: "add team members",
  TAB_NAVIGATOR: "tabs",
  HOME_NAVIGATOR: "home navigator",
  TEAM_NAVIGATOR: "team navigator",
  CHALLENGE_NAVIGATOR: "challenge navigator",
  ADD_CHALLENGE_USER: "add challenge user",
  COMPARISON_NAVIGATOR: "comparison navigator",
  PROFILE_EDIT: "edit profile",
  ACTIVITY: "Activities",
  SELF_COMPARER: "self comparer",
  OTHER_COMPARER: "other comparer",
  SELF_COMPARER_HOME: "self comparer home",
  OTHER_COMPARER_HOME: "other comparer home",
});
